version: '3'

services:
  frontend:
    build: frontend/.
    restart: on-failure
    ports:
      - "9991:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/fence
      SECRET_KEY: ${SECRET_KEY}
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "9993:27017"