version: '3'

services:
  frontend:
    build: frontend/.
    restart: on-failure
    ports:
      - "9991:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "9993:27017"
    environment:
      environment:
      MONGO_INITDB_ROOT_USERNAME: root
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9992:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/